# This file was auto-generado por la CLI de Firebase
# https://github.com/firebase/firebase-tools

name: Deploy Equipo-Azul
on:
  push:
    branches:
      - main
    paths:
      - emergency-control-azul/**
      - back-control-incendios-azul/**
  pull_request:
    branches:
      - main
    paths:
      - emergency-control-azul/**
      - back-control-incendios-azul/**

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run emergency-control-azul:build

  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run emergency-control-azul:test

  lint_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run emergency-control-azul:lint

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run back-control-incendios-azul:build

  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run back-control-incendios-azul:test

  lint_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional
      - run: npx nx run back-control-incendios-azul:lint

  build_and_deploy:
    needs: [build_frontend, build_backend] 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install @nx/nx-linux-x64-gnu @rollup/rollup-linux-x64-gnu @nx/webpack @nx/cypress
      - run: npm install --include=optional && npx nx run emergency-control-azul:build
      - name: Deploy to Firebase
        if: ${{ github.event_name == 'push' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERGENCIASUDOAPP }}'
          channelId: live
          projectId: emergenciasudoapp
          name: emergenciasPage
          target: equipo-azul
      - name: Deploy to Firebase
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_EMERGENCIASUDOAPP }}'
          channelId: staging
          projectId: emergenciasudoapp
          name: emergenciasPage
          target: equipo-azul
